fix text split when creating tags
FCSCOpendata/ckanext-vocabulary pull request #3
Opened 2022-03-02 17:09 UTC by steveoni

this pr fix text split when creating single tags

2022-03-03 03:52 UTC, sagargg requested changes

2022-03-03 03:52 UTC, sagargg commented on ckanext/vocabulary/blueprints/vocabulary.py
> +            get_action('tag_create')(context, tag_dict)
@steveoni  can we display success and error flash messages.  something like 

``` python
try:
      get_action('tag_create')(context, tag_dict)
      h.flash_success(u"Tag sucessfully added to the category.")
except ValidationError as e:
      h.flash_error(e.error_dict)
```

2022-03-03 03:52 UTC, sagargg commented on ckanext/vocabulary/blueprints/vocabulary.py
>              tags = []
looks like tags = [] is  not in used

2022-03-03 03:52 UTC, sagargg commented on ckanext/vocabulary/blueprints/vocabulary.py
>          create_vocab = get_action('vocabulary_create')(context, data_dict)
Can we display flash messages on success or when errors happen.

2022-03-03 15:13 UTC, sagargg commented
@steveoni  can reduce the button margin for the label. 

<img width="924" alt="Screen Shot 2022-03-03 at 8 56 44 PM" src="https://user-images.githubusercontent.com/87696933/156593115-66dba63c-77c6-4cb0-874e-e461d33d9332.png">

2022-03-03 15:16 UTC, sagargg commented
Same on this page also, reduce button margin. It looks  little bit untidy. 
<img width="889" alt="Screen Shot 2022-03-03 at 9 00 48 PM" src="https://user-images.githubusercontent.com/87696933/156593711-ee344ceb-6030-48a4-99ec-f7696de8cffe.png">

2022-03-03 15:39 UTC, osahon-okungbowa commented
@steveoni i agree with @sagargg . Also, please reduce the font size of the "Add Tag" headings. It should be slightly smaller than the main heading

2022-03-04 09:02 UTC, steveoni commented
@osahon-okungbowa and @sagargg thanks for the comment and pointing that out. here is an update.

![Screenshot 2022-03-04 at 09 59 20](https://user-images.githubusercontent.com/20904032/156732624-b88a9343-325b-44c1-af8b-5c06dc71793b.png)


![Screenshot 2022-03-04 at 09 59 36](https://user-images.githubusercontent.com/20904032/156732680-66c44574-d3a4-470f-b87c-9681a3fa7f2a.png)

![Screenshot 2022-03-04 at 10 00 01](https://user-images.githubusercontent.com/20904032/156732779-93d3ae40-7822-4788-b240-a5ab694f687d.png)

2022-03-04 09:13 UTC, sagargg commented
@steveoni  Tags filed alignment is little compared to other fields.   
 
<img width="1440" alt="Screen Shot 2022-03-04 at 2 55 22 PM" src="https://user-images.githubusercontent.com/87696933/156734038-7e82ef9c-f090-40eb-a711-7e07b4514d9d.png">

2022-03-04 09:16 UTC, steveoni commented
> @steveoni Tags filed alignment is little compared to other fields.
> 
> <img alt="Screen Shot 2022-03-04 at 2 55 22 PM" width="1440" src="https://user-images.githubusercontent.com/87696933/156734038-7e82ef9c-f090-40eb-a711-7e07b4514d9d.png">

is a different section of it self and it think is okay

2022-03-04 09:16 UTC, sagargg commented
@steveoni  okay. I'll merge this for now.

2022-03-04 09:17 UTC, sagargg commented
**LGTM**

2022-03-04 09:17 UTC, merged